CREATE USER Karlen WITH PASSWORD 'password1'
CREATE USER Poxos WITH PASSWORD 'password2'

CREATE DATABASE my_db;
GRANT ALL PRIVILEGES ON DATABASE my_db TO karlen;

REVOKE ALL ON DATABASE my_db FROM PUBLIC ;
GRANT CONNECT ON DATABASE my_db TO karlen;

ALTER USER karlen WITH PASSWORD 'passw1';
ALTER USER poxos WITH PASSWORD 'passw2';
